default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: home_front_development

test:
  <<: *default
  database: home_front_test

production:
  adapter: postgresql
  database: home_front
